import JSZip from "jszip";
import { RootJson, WidgetEntry, FontJsonItem } from "./types";
import { prettyJson, fontJsonFileText } from "./IWFParser";
import { ProjectFiles } from "../core/ProjectFiles";

/**
 * Port of MainWindow.on_create_zip_file().
 *
 * Differences from the original, called out explicitly:
 *  - The desktop version looked for a background file hard-coded to
 *    "files0.png" instead of the actual `bkground` field, which meant
 *    re-uploading a background (files1.png, files2.png, ...) silently
 *    broke ZIP export. This port uses the real `bkground` filename.
 *  - `preview.png` is generated by "Save Preview" but, in the original
 *    source, was never actually written into the ZIP even though a
 *    comment suggested it should be. This port fixes that omission and
 *    includes preview.png when one has been generated, since that
 *    matches the app's evident intent.
 *  - There is no local project_dir; all bytes come from the in-memory
 *    ProjectFiles table populated as assets are uploaded/imported.
 */
export async function exportProjectZip(
  root: RootJson,
  widgetList: WidgetEntry[],
  fontItems: FontJsonItem[],
  files: ProjectFiles,
): Promise<Blob> {
  const zip = new JSZip();

  zip.file("iwf.json", prettyJson(root));

  if (fontItems.length > 0) {
    // FIXED: Use "item" array instead of "font" to match the original format
    zip.file("font.json", JSON.stringify({ item: fontItems }));
  }

  if (root.bkground) {
    const blob = files.get(root.bkground);
    if (blob) zip.file(root.bkground, blob);
  }

  const previewBlob = files.get("preview.png");
  if (previewBlob) zip.file("preview.png", previewBlob);

  for (const entry of widgetList) {
    if (entry.json.widget === "watch") {
      for (const handKey of ["hour", "minute", "second"] as const) {
        const fname = entry.json[handKey];
        if (typeof fname === "string" && fname) {
          const blob = files.get(fname);
          if (blob) zip.file(fname, blob);
        }
      }
    } else if (entry.json.widget === "custom") {
      const folder = entry.fontFolder;
      if (folder) {
        for (const [path, blob] of files.entriesUnderFolder(folder)) {
          zip.file(path, blob);
        }
      }
    }
  }

  return zip.generateAsync({ type: "blob" });
}

/** Triggers a browser download of a Blob under the given filename. */
export function downloadBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 10_000);
}